apiVersion: v1
kind: Secret
metadata:
  name: lead-scoring-backend
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
data:
{{- range $key, $val := .Values.secret_vars }}
  {{ $key }}: {{ $val | b64enc  }}
{{- end }}
